### ISSUE TITLE
[Question] Could Hubot alone do all that Janky does?

### ISSUE THREAD

**Issue by judoole** [github/janky#218]
Trying to wrap my head around the main reason why Janky is the middleman between Hubot and Jenkins. Is it because the logic demands too much of Coffeescript or maybe a security issue? A big disclaimer here is that I have barely used and seen Janky beyond Getting Started.

**Comment by mattr-** [comment]
IMO, there are a few reasons why Janky exists besides just doing everything with Hubot and Jenkins:
 - Janky stores the build output from Jenkins indefinitely, which means that build that happened last week that's long since been deleted from Jenkins is still available, if needed.
 - Janky is a minimal syle replacement for Jenkins' UI, which is not something that you can do with Hubot.
 - Hubot add ons for handling GitHub's API hasn't always been the best, IME. The ruby libraries were more mature at the time, and so it made sense to use those to bridge Jenkins and Hubot than just using Hubot standalone.

Hope this helps answer your question. It very well could be that Janky isn't really required nowadays, and  that it'll just sit here collecting dust, much like it has the last year or so.

**Comment by judoole** [comment]
Thanks for an excellent answer @mattr- 
I think storage of build output is a very nice feature and perhaps demands some considerable effort to replicate in Hubot. Apart from that I did some initial testing using the Github webhooks directly to Hubots Express server. Used [mustache](https://github.com/janl/mustache.js/) for templating the Jenkins-jobs. Looked like it could work, so I might put some more effort into it.
